'use client'

import { ArrowRight, CalendarCheck, Check, ChevronDown, Clock3, HeartHandshake, Menu, MessageCircle, Play, Sparkles, Star, X } from 'lucide-react'
import { useState } from 'react'
import { Button } from '@/components/ui/button'

export function MarketingLanding({ onOpenApp }: { onOpenApp: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const [sent, setSent] = useState(false)
  return <div className="landing-shell">
    <header className="site-header"><a href="#inicio" className="brand-lockup"><span className="brand-mark"><Sparkles size={15} /></span><span>agenda<span className="text-primary">.</span></span></a><nav className="desktop-nav"><a href="#funciones">Funciones</a><a href="#como-funciona">Cómo funciona</a><a href="#precios">Precios</a><a href="#contacto">Contacto</a></nav><div className="header-actions"><button className="login-link" onClick={onOpenApp}>Iniciar sesión</button><Button onClick={onOpenApp} className="rounded-full">Probar gratis <ArrowRight data-icon="inline-end" /></Button></div><button className="mobile-menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menú">{menuOpen ? <X /> : <Menu />}</button></header>
    {menuOpen && <nav className="mobile-nav"><a href="#funciones" onClick={() => setMenuOpen(false)}>Funciones</a><a href="#como-funciona" onClick={() => setMenuOpen(false)}>Cómo funciona</a><a href="#precios" onClick={() => setMenuOpen(false)}>Precios</a><a href="#contacto" onClick={() => setMenuOpen(false)}>Contacto</a><Button onClick={onOpenApp} className="rounded-full">Entrar al workspace</Button></nav>}
    <main>
      <section id="inicio" className="hero-section"><div className="hero-copy"><span className="eyebrow hero-eyebrow"><span className="pulse-dot" /> La agenda que trabaja contigo</span><h1>Más tiempo para <em>lo que importa.</em></h1><p>Gestiona tus citas, clientes y pagos en un solo lugar. agenda. hace que dirigir tu práctica se sienta sencillo.</p><div className="hero-actions"><Button onClick={onOpenApp} size="lg" className="rounded-full">Comenzar gratis <ArrowRight data-icon="inline-end" /></Button><button className="watch-button"><span className="play-icon"><Play size={13} fill="currentColor" /></span> Ver cómo funciona</button></div><div className="hero-proof"><div className="avatar-stack"><span>AG</span><span>MR</span><span>LC</span><span>+</span></div><p><strong>+2,400 profesionales</strong><br />organizan mejor su día</p></div></div><div className="hero-visual"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="calendar-card"><div className="calendar-top"><div><span className="eyebrow">Miércoles, 14 mayo</span><h3>Tu día, bajo control</h3></div><span className="mini-brand"><Sparkles size={13} /></span></div><div className="calendar-grid"><div className="calendar-labels"><span>09</span><span>10</span><span>11</span><span>12</span><span>13</span></div><div className="calendar-events"><div className="event event-blue"><strong>Sesión de terapia</strong><small>09:00 — 09:45 · Sofía Ramírez</small></div><div className="event event-coral"><strong>Consulta inicial</strong><small>10:30 — 11:30 · Mateo López</small></div><div className="event event-mint"><strong>Espacio libre</strong><small>12:00 — 13:00</small></div></div></div><div className="calendar-footer"><span><span className="status-dot" /> 4 citas confirmadas</span><span className="calendar-arrow">↗</span></div></div><div className="floating-stat"><span className="stat-icon"><CalendarCheck size={16} /></span><div><strong>94.2%</strong><small>asistencia este mes</small></div><span className="stat-up">+2.1%</span></div></div></section>
      <section className="trust-strip"><span>Diseñado para profesionales que hacen la diferencia</span><div><b>psicología</b><b>barbería</b><b>fitness</b><b>bienestar</b></div></section>
      <section id="funciones" className="features-section section-wrap"><div className="section-heading"><span className="eyebrow">Todo en un solo lugar</span><h2>Tu negocio, <em>más simple.</em></h2><p>Las herramientas que necesitas para crecer, sin la complejidad que no necesitas.</p></div><div className="feature-grid"><Feature icon={<CalendarCheck />} title="Calendario inteligente" text="Tus clientes reservan cuando quieren. Tú ves todo en una vista clara y flexible." tone="blue" /><Feature icon={<HeartHandshake />} title="Clientes que vuelven" text="Conoce mejor a tus clientes, guarda sus notas y crea relaciones duraderas." tone="coral" /><Feature icon={<Clock3 />} title="Pagos sin fricción" text="Cobra por adelantado y olvídate de perseguir pagos pendientes." tone="mint" /></div></section>
      <section id="como-funciona" className="process-section section-wrap"><div className="process-visual"><div className="phone-frame"><div className="phone-bar" /><div className="phone-content"><span className="eyebrow">Tu semana</span><h4>Hola, María</h4><div className="phone-date">MAY <strong>14</strong> JUN</div><div className="phone-booking"><span>09:00</span><div><strong>Sofía Ramírez</strong><small>Sesión de terapia</small></div><Check /></div><div className="phone-booking muted-booking"><span>10:30</span><div><strong>Mateo López</strong><small>Consulta inicial</small></div><Check /></div><Button className="w-full rounded-full">+ Nueva cita</Button></div></div></div><div className="process-copy"><span className="eyebrow">Así de fácil</span><h2>Tu día empieza<br /><em>con claridad.</em></h2><p>Deja atrás las hojas de cálculo y los mensajes interminables. agenda. automatiza lo repetitivo para que tú puedas enfocarte en tu trabajo.</p><div className="process-points"><Point number="01" title="Configura tu espacio" text="Añade tus servicios, horarios y disponibilidad." /><Point number="02" title="Comparte tu enlace" text="Tus clientes reservan solos, 24/7." /><Point number="03" title="Haz crecer tu práctica" text="Mide, mejora y disfruta de tu libertad." /></div></div></section>
      <section id="precios" className="pricing-section section-wrap"><div className="section-heading centered"><span className="eyebrow">Precios transparentes</span><h2>Empieza simple,<br /><em>crece a tu ritmo.</em></h2><p>Sin contratos. Sin sorpresas. Cancela cuando quieras.</p></div><div className="pricing-card"><div><span className="eyebrow">Plan esencial</span><h3>Todo lo que necesitas<br />para empezar.</h3><p>Perfecto para profesionales independientes que quieren trabajar mejor.</p></div><div className="price"><strong>Gratis</strong><span>para siempre</span><Button onClick={onOpenApp} className="rounded-full">Crear mi cuenta <ArrowRight data-icon="inline-end" /></Button></div><ul><li><Check /> Calendario y reservas ilimitadas</li><li><Check /> Gestión de clientes</li><li><Check /> Página de reservas personalizada</li><li><Check /> Soporte por email</li></ul></div></section>
      <section id="contacto" className="contact-section section-wrap"><div><span className="eyebrow">Hablemos</span><h2>¿Tienes alguna<br /><em>pregunta?</em></h2><p>Estamos aquí para ayudarte a sacar el máximo partido a tu tiempo.</p><div className="contact-detail"><MessageCircle /><span>hola@agenda.app</span></div></div><form className="contact-form" onSubmit={(e) => { e.preventDefault(); setSent(true) }}>{sent ? <div className="success-message"><span className="success-icon"><Check /></span><h3>Mensaje enviado.</h3><p>Te responderemos muy pronto en tu email.</p><button type="button" onClick={() => setSent(false)}>Enviar otro mensaje</button></div> : <><label>Tu nombre<input required placeholder="María González" /></label><label>Tu email<input required type="email" placeholder="maria@ejemplo.com" /></label><label>¿Cómo podemos ayudarte?<textarea required placeholder="Cuéntanos un poco..." rows={3} /></label><Button type="submit" className="rounded-full">Enviar mensaje <ArrowRight data-icon="inline-end" /></Button></>}</form></section>
    </main><footer className="site-footer"><a href="#inicio" className="brand-lockup"><span className="brand-mark"><Sparkles size={15} /></span><span>agenda<span className="text-primary">.</span></span></a><p>Menos gestión. Más propósito.</p><div><a href="#funciones">Funciones</a><a href="#precios">Precios</a><a href="#contacto">Contacto</a><span>© 2026 agenda.</span></div></footer>
  </div>
}
function Feature({ icon, title, text, tone }: { icon: React.ReactNode; title: string; text: string; tone: string }) { return <article className="feature-card"><span className={`feature-icon ${tone}`}>{icon}</span><h3>{title}</h3><p>{text}</p><a href="#contacto">Conoce más <ArrowRight data-icon="inline-end" /></a></article> }
function Point({ number, title, text }: { number: string; title: string; text: string }) { return <div className="process-point"><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></div> }

export function Workspace({ onHome }: { onHome: () => void }) {
  const [module, setModule] = useState('Resumen')
  const modules = ['Resumen', 'Calendario', 'Clientes', 'Servicios', 'Pagos', 'Notificaciones', 'Configuración']
  const details: Record<string, { title: string; description: string; items: string[] }> = {
    Resumen: { title: 'Tu día, bajo control.', description: 'Una vista rápida de lo importante en tu práctica.', items: ['4 citas para hoy', '$4,280 ingresos estimados', '94.2% tasa de asistencia'] },
    Calendario: { title: 'Calendario de reservas.', description: 'Organiza tu semana y encuentra espacios libres.', items: ['09:00 · Sofía Ramírez', '10:30 · Mateo López', '12:00 · Espacio disponible'] },
    Clientes: { title: 'Clientes que vuelven.', description: 'Gestiona tus relaciones y mantén cada detalle a mano.', items: ['Sofía Ramírez · 12 sesiones', 'Mateo López · 4 sesiones', 'Valentina Cruz · 8 sesiones'] },
    Servicios: { title: 'Tus servicios.', description: 'Define lo que ofreces, duración y precio.', items: ['Terapia individual · $55', 'Consulta inicial · $70', 'Seguimiento online · $35'] },
    Pagos: { title: 'Pagos sin fricción.', description: 'Consulta ingresos y cobros pendientes.', items: ['$2,480 cobrados este mes', '3 pagos pendientes', 'Último cobro · $55'] },
    Notificaciones: { title: 'Todo al día.', description: 'Recordatorios y avisos importantes para tu agenda.', items: ['2 confirmaciones nuevas', '1 recordatorio enviado', 'Sin incidencias'] },
    Configuración: { title: 'Configura tu espacio.', description: 'Personaliza tu perfil, horarios y preferencias.', items: ['Perfil profesional', 'Horarios de atención', 'Página pública de reservas'] },
  }
  const current = details[module]
  return <div className="workspace-placeholder"><header className="site-header"><button onClick={onHome} className="brand-lockup"><span className="brand-mark"><Sparkles size={15} /></span><span>agenda<span className="text-primary">.</span></span></button><Button onClick={onHome} variant="outline" className="rounded-full">Volver al inicio</Button></header><div className="workspace-layout"><aside className="workspace-sidebar"><span className="eyebrow">Workspace</span><nav>{modules.map((item) => <button key={item} className={module === item ? 'workspace-nav-active' : ''} onClick={() => setModule(item)}>{item}{item === 'Pagos' && <span>3</span>}</button>)}</nav></aside><main className="workspace-main"><span className="eyebrow">Mi workspace / {module}</span><h1>{current.title}</h1><p className="workspace-description">{current.description}</p><div className="workspace-cards">{current.items.map((item, index) => <article className="workspace-card" key={item}><span className="workspace-card-number">0{index + 1}</span><div><strong>{item}</strong><small>{module === 'Calendario' ? 'Hoy' : 'Actualizado recientemente'}</small></div><ArrowRight /></article>)}</div><Button className="rounded-full" onClick={() => setModule('Calendario')}>Ver agenda completa <ArrowRight data-icon="inline-end" /></Button></main></div></div>
}
