'use client'

import { ArrowRight, CalendarCheck, Check, ChevronDown, Clock3, HeartHandshake, Menu, MessageCircle, Play, Sparkles, Star, X } from 'lucide-react'
import { useState } from 'react'
import { Button } from '@/components/ui/button'

export function MarketingLanding({ onOpenApp }: { onOpenApp: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const [sent, setSent] = useState(false)
  return <div className="landing-shell">
    <header className="site-header"><a href="#inicio" className="brand-lockup"><span className="brand-mark"><Sparkles size={15} /></span><span>agenda<span className="text-primary">.</span></span></a><nav className="desktop-nav"><a href="#funciones">Funciones</a><a href="#como-funciona">Cómo funciona</a><a href="#precios">Precios</a><a href="#contacto">Contacto</a></nav><div className="header-actions"><button className="login-link" onClick={onOpenApp}>Iniciar sesión</button><Button onClick={onOpenApp} className="rounded-full">Probar gratis <ArrowRight data-icon="inline-end" /></Button></div><button className="mobile-menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menú">{menuOpen ? <X /> : <Menu />}</button></header>
    {menuOpen && <nav className="mobile-nav"><a href="#funciones" onClick={() => setMenuOpen(false)}>Funciones</a><a href="#como-funciona" onClick={() => setMenuOpen(false)}>Cómo funciona</a><a href="#precios" onClick={() => setMenuOpen(false)}>Precios</a><a href="#contacto" onClick={() => setMenuOpen(false)}>Contacto</a><Button onClick={onOpenApp} className="rounded-full">Entrar al workspace</Button></nav>}
    <main>
      <section id="inicio" className="hero-section"><div className="hero-copy"><span className="eyebrow hero-eyebrow"><span className="pulse-dot" /> La agenda que trabaja contigo</span><h1>Más tiempo para <em>lo que importa.</em></h1><p>Gestiona tus citas, clientes y pagos en un solo lugar. agenda. hace que dirigir tu práctica se sienta sencillo.</p><div className="hero-actions"><Button onClick={onOpenApp} size="lg" className="rounded-full">Comenzar gratis <ArrowRight data-icon="inline-end" /></Button><button className="watch-button"><span className="play-icon"><Play size={13} fill="currentColor" /></span> Ver cómo funciona</button></div><div className="hero-proof"><div className="avatar-stack"><span>AG</span><span>MR</span><span>LC</span><span>+</span></div><p><strong>+2,400 profesionales</strong><br />organizan mejor su día</p></div></div><div className="hero-visual"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="calendar-card"><div className="calendar-top"><div><span className="eyebrow">Miércoles, 14 mayo</span><h3>Tu día, bajo control</h3></div><span className="mini-brand"><Sparkles size={13} /></span></div><div className="calendar-grid"><div className="calendar-labels"><span>09</span><span>10</span><span>11</span><span>12</span><span>13</span></div><div className="calendar-events"><div className="event event-blue"><strong>Sesión de terapia</strong><small>09:00 — 09:45 · Sofía Ramírez</small></div><div className="event event-coral"><strong>Consulta inicial</strong><small>10:30 — 11:30 · Mateo López</small></div><div className="event event-mint"><strong>Espacio libre</strong><small>12:00 — 13:00</small></div></div></div><div className="calendar-footer"><span><span className="status-dot" /> 4 citas confirmadas</span><span className="calendar-arrow">↗</span></div></div><div className="floating-stat"><span className="stat-icon"><CalendarCheck size={16} /></span><div><strong>94.2%</strong><small>asistencia este mes</small></div><span className="stat-up">+2.1%</span></div></div></section>
      <section className="trust-strip"><span>Diseñado para profesionales que hacen la diferencia</span><div><b>psicología</b><b>barbería</b><b>fitness</b><b>bienestar</b></div></section>
      <section id="funciones" className="features-section section-wrap"><div className="section-heading"><span className="eyebrow">Todo en un solo lugar</span><h2>Tu negocio, <em>más simple.</em></h2><p>Las herramientas que necesitas para crecer, sin la complejidad que no necesitas.</p></div><div className="feature-grid"><Feature icon={<CalendarCheck />} title="Calendario inteligente" text="Tus clientes reservan cuando quieren. Tú ves todo en una vista clara y flexible." tone="blue" /><Feature icon={<HeartHandshake />} title="Clientes que vuelven" text="Conoce mejor a tus clientes, guarda sus notas y crea relaciones duraderas." tone="coral" /><Feature icon={<Clock3 />} title="Pagos sin fricción" text="Cobra por adelantado y olvídate de perseguir pagos pendientes." tone="mint" /></div></section>
      <section id="como-funciona" className="process-section section-wrap"><div className="process-visual"><div className="phone-frame"><div className="phone-bar" /><div className="phone-content"><span className="eyebrow">Tu semana</span><h4>Hola, María</h4><div className="phone-date">MAY <strong>14</strong> JUN</div><div className="phone-booking"><span>09:00</span><div><strong>Sofía Ramírez</strong><small>Sesión de terapia</small></div><Check /></div><div className="phone-booking muted-booking"><span>10:30</span><div><strong>Mateo López</strong><small>Consulta inicial</small></div><Check /></div><Button className="w-full rounded-full">+ Nueva cita</Button></div></div></div><div className="process-copy"><span className="eyebrow">Así de fácil</span><h2>Tu día empieza<br /><em>con claridad.</em></h2><p>Deja atrás las hojas de cálculo y los mensajes interminables. agenda. automatiza lo repetitivo para que tú puedas enfocarte en tu trabajo.</p><div className="process-points"><Point number="01" title="Configura tu espacio" text="Añade tus servicios, horarios y disponibilidad." /><Point number="02" title="Comparte tu enlace" text="Tus clientes reservan solos, 24/7." /><Point number="03" title="Haz crecer tu práctica" text="Mide, mejora y disfruta de tu libertad." /></div></div></section>
      <section id="precios" className="pricing-section section-wrap"><div className="section-heading centered"><span className="eyebrow">Precios transparentes</span><h2>Empieza simple,<br /><em>crece a tu ritmo.</em></h2><p>Sin contratos. Sin sorpresas. Cancela cuando quieras.</p></div><div className="pricing-card"><div><span className="eyebrow">Plan esencial</span><h3>Todo lo que necesitas<br />para empezar.</h3><p>Perfecto para profesionales independientes que quieren trabajar mejor.</p></div><div className="price"><strong>Gratis</strong><span>para siempre</span><Button onClick={onOpenApp} className="rounded-full">Crear mi cuenta <ArrowRight data-icon="inline-end" /></Button></div><ul><li><Check /> Calendario y reservas ilimitadas</li><li><Check /> Gestión de clientes</li><li><Check /> Página de reservas personalizada</li><li><Check /> Soporte por email</li></ul></div></section>
      <section id="contacto" className="contact-section section-wrap"><div><span className="eyebrow">Hablemos</span><h2>¿Tienes alguna<br /><em>pregunta?</em></h2><p>Estamos aquí para ayudarte a sacar el máximo partido a tu tiempo.</p><div className="contact-detail"><MessageCircle /><span>hola@agenda.app</span></div></div><form className="contact-form" onSubmit={(e) => { e.preventDefault(); setSent(true) }}>{sent ? <div className="success-message"><span className="success-icon"><Check /></span><h3>Mensaje enviado.</h3><p>Te responderemos muy pronto en tu email.</p><button type="button" onClick={() => setSent(false)}>Enviar otro mensaje</button></div> : <><label>Tu nombre<input required placeholder="María González" /></label><label>Tu email<input required type="email" placeholder="maria@ejemplo.com" /></label><label>¿Cómo podemos ayudarte?<textarea required placeholder="Cuéntanos un poco..." rows={3} /></label><Button type="submit" className="rounded-full">Enviar mensaje <ArrowRight data-icon="inline-end" /></Button></>}</form></section>
    </main><footer className="site-footer"><a href="#inicio" className="brand-lockup"><span className="brand-mark"><Sparkles size={15} /></span><span>agenda<span className="text-primary">.</span></span></a><p>Menos gestión. Más propósito.</p><div><a href="#funciones">Funciones</a><a href="#precios">Precios</a><a href="#contacto">Contacto</a><span>© 2026 agenda.</span></div></footer>
  </div>
}
function Feature({ icon, title, text, tone }: { icon: React.ReactNode; title: string; text: string; tone: string }) { return <article className="feature-card"><span className={`feature-icon ${tone}`}>{icon}</span><h3>{title}</h3><p>{text}</p><a href="#contacto">Conoce más <ArrowRight data-icon="inline-end" /></a></article> }
function Point({ number, title, text }: { number: string; title: string; text: string }) { return <div className="process-point"><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></div> }

export function Workspace({ onHome }: { onHome: () => void }) {
  const [module, setModule] = useState('Resumen')
  const [showForm, setShowForm] = useState(false)
  const [toast, setToast] = useState('')
  const [search, setSearch] = useState('')
  const modules = [
    { name: 'Resumen', icon: Sparkles }, { name: 'Calendario', icon: CalendarCheck },
    { name: 'Clientes', icon: HeartHandshake }, { name: 'Servicios', icon: Clock3 },
    { name: 'Pagos', icon: ArrowRight }, { name: 'Notificaciones', icon: MessageCircle },
    { name: 'Administración', icon: Star }, { name: 'Configuración', icon: ChevronDown },
  ]
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const actionLabel = module === 'Calendario' ? 'Nueva cita' : module === 'Clientes' ? 'Nuevo cliente' : module === 'Servicios' ? 'Nuevo servicio' : 'Crear registro'
  const rows = module === 'Clientes' ? ['Sofía Ramírez', 'Mateo López', 'Valentina Cruz', 'Ana Torres'] : module === 'Servicios' ? ['Terapia individual', 'Consulta inicial', 'Seguimiento online', 'Plan mensual'] : ['Sofía Ramírez · 09:00', 'Mateo López · 10:30', 'Valentina Cruz · 14:00', 'Ana Torres · 16:30']
  const filteredRows = rows.filter((row) => row.toLowerCase().includes(search.toLowerCase()))
  const title = module === 'Administración' ? 'Centro de administración' : module === 'Resumen' ? 'Buenos días, María' : module
  return <div className="min-h-screen bg-background">
    <header className="sticky top-0 z-30 flex h-18 items-center justify-between border-b border-border/70 bg-background/90 px-5 backdrop-blur-xl sm:px-8 lg:px-10">
      <button onClick={onHome} className="brand-lockup"><span className="brand-mark"><Sparkles size={15} /></span><span>agenda<span className="text-primary">.</span></span></button>
      <div className="flex items-center gap-3"><button onClick={() => notify('No tienes notificaciones nuevas')} className="relative rounded-full border border-border p-2.5 text-muted-foreground hover:text-foreground" aria-label="Notificaciones"><MessageCircle size={17} /></button><div className="hidden items-center gap-2 border-l border-border pl-4 sm:flex"><span className="flex size-8 items-center justify-center rounded-full bg-accent text-xs font-semibold">MG</span><span className="text-sm font-medium">María González</span></div><Button onClick={onHome} variant="outline" size="sm" className="rounded-full">Salir</Button></div>
    </header>
    <div className="mx-auto flex max-w-[1440px]">
      <aside className="hidden w-64 shrink-0 border-r border-border/70 px-5 py-8 lg:block"><p className="eyebrow px-3">Workspace</p><nav className="mt-5 flex flex-col gap-1">{modules.map(({ name, icon: Icon }) => <button key={name} onClick={() => setModule(name)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition-colors ${module === name ? 'bg-accent font-semibold text-accent-foreground' : 'text-muted-foreground hover:bg-card hover:text-foreground'}`}><Icon size={17} />{name}{name === 'Pagos' && <span className="ml-auto rounded-full bg-primary px-2 py-0.5 text-[10px] text-primary-foreground">3</span>}</button>)}</nav><div className="mt-10 rounded-2xl border border-border bg-card p-4"><span className="eyebrow">Tu plan</span><strong className="mt-2 block text-sm">Esencial</strong><div className="mt-3 h-1.5 rounded-full bg-secondary"><div className="h-full w-2/3 rounded-full bg-primary" /></div><p className="mt-2 text-[11px] text-muted-foreground">68 de 100 citas usadas</p><button onClick={() => notify('La mejora de plan estará disponible pronto')} className="mt-3 text-xs font-semibold text-primary">Ver opciones</button></div></aside>
      <main className="min-w-0 flex-1 px-5 py-8 sm:px-8 lg:px-10 lg:py-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="eyebrow">Mi workspace / {module}</span><h1 className="mt-3 text-3xl font-semibold tracking-[-.06em] sm:text-5xl">{title}</h1><p className="mt-2 text-sm text-muted-foreground">Aquí tienes todo lo que necesitas para dirigir tu práctica.</p></div><Button onClick={() => setShowForm(true)} className="rounded-full"><span>+</span>{actionLabel}</Button></div>
        <div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Citas este mes" value="128" change="+12.5%" /><Metric label="Ingresos" value="$4,280" change="+8.2%" /><Metric label="Clientes activos" value="86" change="+5.4%" /><Metric label="Asistencia" value="94.2%" change="+2.1%" /></div>
        {module === 'Administración' ? <AdminPanel onNotify={notify} /> : <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.8fr]"><section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{module === 'Resumen' ? 'Actividad de la semana' : `Gestiona ${module.toLowerCase()}`}</h2><p className="mt-1 text-xs text-muted-foreground">Últimos 7 días</p></div><div className="flex items-center gap-2"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar..." className="w-32 rounded-lg border border-input bg-background px-3 py-2 text-xs outline-none focus:ring-2 focus:ring-ring/30" /><Button variant="outline" size="sm" onClick={() => notify('Filtro aplicado')}>Filtrar</Button></div></div>{module === 'Resumen' ? <WeeklyChart /> : <div className="mt-6 flex flex-col gap-2">{filteredRows.map((row, index) => <div key={row} className="flex items-center gap-3 rounded-xl border border-border/70 p-3"><span className="flex size-8 items-center justify-center rounded-lg bg-accent text-xs font-semibold text-primary">0{index + 1}</span><span className="flex-1 text-sm font-medium">{row}</span><span className="rounded-full bg-secondary px-2 py-1 text-[10px] text-muted-foreground">Activo</span><button onClick={() => notify(`Editando ${row}`)} className="text-xs font-semibold text-primary">Editar</button></div>)}</div>}</section><section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Próximas citas</h2><p className="mt-1 text-xs text-muted-foreground">Hoy, miércoles 14 mayo</p></div><button onClick={() => setModule('Calendario')} className="text-xs font-semibold text-primary">Ver todas</button></div><div className="mt-6 flex flex-col gap-4"><Appointment time="09:00" name="Sofía Ramírez" service="Sesión de terapia" /><Appointment time="10:30" name="Mateo López" service="Consulta inicial" /><Appointment time="14:00" name="Valentina Cruz" service="Seguimiento online" /></div></section></div>}
      </main>
    </div>{showForm && <QuickForm title={actionLabel} onClose={() => setShowForm(false)} onSave={() => { setShowForm(false); notify(`${actionLabel} guardado correctamente`) }} />}{toast && <div className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-full bg-foreground px-5 py-3 text-sm text-background shadow-xl">{toast}</div>}
  </div>
}
function Metric({ label, value, change }: { label: string; value: string; change: string }) { return <article className="rounded-2xl border border-border bg-card p-5"><p className="text-xs text-muted-foreground">{label}</p><div className="mt-3 flex items-end justify-between gap-2"><strong className="text-2xl tracking-[-.05em]">{value}</strong><span className="rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-medium text-emerald-700">{change}</span></div></article> }
function WeeklyChart() { return <div className="mt-8 flex h-52 items-end gap-2 border-b border-border pb-0 sm:gap-5">{[44, 67, 52, 88, 64, 78, 38].map((height, i) => <div key={i} className="flex flex-1 flex-col items-center gap-2"><div className={`w-full rounded-t-lg ${i === 3 ? 'bg-primary' : 'bg-accent'}`} style={{ height: `${height}%` }} /><span className="text-[10px] text-muted-foreground">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'][i]}</span></div>)}</div> }
function Appointment({ time, name, service }: { time: string; name: string; service: string }) { return <div className="flex gap-3"><span className="w-10 pt-1 text-xs font-semibold text-primary">{time}</span><div className="flex-1 rounded-xl bg-secondary/60 p-3"><strong className="block text-sm">{name}</strong><span className="mt-1 block text-xs text-muted-foreground">{service}</span></div></div> }
function QuickForm({ title, onClose, onSave }: { title: string; onClose: () => void; onSave: () => void }) { return <div className="fixed inset-0 z-40 flex items-center justify-center bg-foreground/30 p-5 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl border border-border bg-card p-6 shadow-2xl"><div className="flex items-center justify-between"><div><span className="eyebrow">Nuevo registro</span><h2 className="mt-2 text-2xl font-semibold tracking-[-.05em]">{title}</h2></div><button onClick={onClose} className="rounded-full border border-border p-2" aria-label="Cerrar"><X size={16} /></button></div><div className="mt-6 flex flex-col gap-4"><label className="flex flex-col gap-2 text-xs font-medium">Nombre<input required className="rounded-xl border border-input bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-ring/30" placeholder="Nombre completo" /></label><label className="flex flex-col gap-2 text-xs font-medium">Email<input type="email" className="rounded-xl border border-input bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-ring/30" placeholder="nombre@email.com" /></label><label className="flex flex-col gap-2 text-xs font-medium">Notas<textarea rows={3} className="rounded-xl border border-input bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-ring/30" placeholder="Añade información relevante..." /></label></div><div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={onClose} className="rounded-full">Cancelar</Button><Button onClick={onSave} className="rounded-full">Guardar registro</Button></div></div></div> }
function AdminPanel({ onNotify }: { onNotify: (message: string) => void }) { return <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><span className="eyebrow">Control central</span><h2 className="mt-2 text-xl font-semibold">Usuarios y permisos</h2></div><Button size="sm" onClick={() => onNotify('Invitación preparada')} className="rounded-full">Invitar usuario</Button></div><div className="mt-6 flex flex-col gap-3">{[['María González','Propietaria','Activo'],['Carlos Méndez','Administrador','Activo'],['Laura Pérez','Colaboradora','Pendiente']].map(([name, role, status]) => <div key={name} className="flex items-center gap-3 rounded-xl border border-border/70 p-3"><span className="flex size-9 items-center justify-center rounded-full bg-accent text-xs font-semibold text-primary">{name.split(' ').map((n) => n[0]).join('')}</span><div className="flex-1"><strong className="block text-sm">{name}</strong><span className="text-xs text-muted-foreground">{role}</span></div><span className="rounded-full bg-secondary px-2 py-1 text-[10px]">{status}</span><button onClick={() => onNotify(`Gestionando a ${name}`)} className="text-xs text-primary">...</button></div>)}</div></section><section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><span className="eyebrow">Actividad reciente</span><h2 className="mt-2 text-xl font-semibold">Logs del sistema</h2><div className="mt-6 flex flex-col gap-4">{['Nueva cita creada por María González','Pago recibido de Sofía Ramírez','Horario actualizado por Carlos Méndez','Usuario invitado a la organización'].map((log, i) => <div key={log} className="flex gap-3 text-sm"><span className="mt-1 size-2 shrink-0 rounded-full bg-primary" /><div><p>{log}</p><span className="text-xs text-muted-foreground">Hace {i + 1} horas</span></div></div>)}</div><Button onClick={() => onNotify('Mostrando todos los logs')} variant="outline" className="mt-6 w-full rounded-full">Ver registro completo</Button></section></div> }
